name: build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-and-build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: ${{ matrix.node-version }}

      - name: Install Deps
        run: npm ci

      - name: Run Tests
        run: npm run test

      - name: Compile
        run: npm run compile